const wordList =
  "PENIS AUGEN FABIO AMPEL WIESE BAUCH TAUBE VOGEL RIESE WONNE WANNE RINNE DIRNE BOOTE NASEN HASEN VASEN SPIEL VIELE BREIT WEITE WETTE ADLER AFFEN CHINA WENIG HONIG HOBEL SUPPE WORTE TORTE JULIA ELITE HODEN";

export default wordList;
